### PR TITLE
Add support for ValidateQuery param in SearchAPI

### PR DESCRIPTION
**Pull request by ishugupta92**

### CODE REVIEW

**Comment by rbriski** [comment]
What happens if `Search` is called with `SearchOptions` and `ValidateQuery` isn't present?

**Comment by ishugupta92** [comment]
The param remains blank like the other params in url and JIRA API uses the default value of `strict` which it would have used if the param had not been present at all.

**Comment by rbriski** [comment]
Tested it.  It does default to strict if the field is blank.  Next time please include that test.  It'll let me merge the change faster.

Thanks!

**Comment by ishugupta92** [comment]
I will make sure to do that next time. Thanks.

**Pull request merged**
