### PR TITLE
Added requesttype

### PR DESCRIPTION
**Pull request by Fank**
# Description

For our current implementation against jira we decided to use this module, but it lacks some requests we need which we would like to contribute in this and upcoming pull requests.
This PR will only focus on the [Requesttype](https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-requesttype/).
I noticed that there is currently a `PagedDTO` struct which contains `[]ìnterface{}` for `values`.
To improve the handing i decided to support this new Requesttype for only golang 1.18+ and use a new struct `PagedDTOT` which is a generic version of the normal one `PagedDTO`.

Information that is useful here:
* **The What**: What is your change doing?

Adds support for non experimental `requesttype` using `serviceDeskID`
https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-requesttype/

* **The Why**: Why is your change useful/needed? What is your use case? (this helps us to understand the real world better)

Currently there is no support for that in this module

* **Type of change**: Things like Bugfix, New feature, Code quality improvements, Dependency upgrade, Documentation, ...

Bugfix
New feature
Code quality improvements

* **Breaking change**: Yes or no? Backward compatible?

No breaking change

* **Related to an issue**: Does this fix or close an issue? Or is related in any kind?

Nope

* **Jira Version + Type**: Which Jira version and type (on-premise / cloud) you have used?

## Example:

Let us know how users can use or test this functionality.

```go
// Example code

jiraClient, err := jira.NewClient(nil, "jiraurl")
if err != nil {
  return err
}

pager, _, err := jiraClient.RequestType.GetWithContext(ctx, 1)
if err != nil {
  return err
}

fmt.Println(pager.Size)

for _, v := range pager.Values {
  fmt.Println(v.Name)

  fmt.Println(v.Icon.Links.IconURLs)
}
```

# Checklist

* [ ] Unit or Integration tests added
  * [ ] Good Path
  * [ ] Error Path
* [x] Commits follow conventions described here:
  * [x] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [x] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [x] Commits are squashed such that
  * [x] There is 1 commit per isolated change
* [x] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Comment by Fank** [comment]
cleaned up code & commit messages, ready for review

**Comment by andygrunwald** [comment]
Hey,

I am very sorry that this pull request has been open for a long time with no final feedback or merge/decline. We work on this project in our spare time, and sometimes, other priorities take over. This is the typical open source dilemma.

#### However, there is news: **We are kicking off v2 of this library 🚀** 

To provide visibility, we created the [Road to v2](https://github.com/andygrunwald/go-jira/milestone/1) Milestone and calling for your feedback in https://github.com/andygrunwald/go-jira/issues/489

The development will take some time; however, I hope you can benefit from the changes.
If you seek priority development for your pull request + you like to sponsor it, please contact me.

#### What does this mean for my pull request?

We will work on this pull request indirectly.
We might merge it during the development or pull parts of it into the new version.
This means that during the development phase, we aim to tackle it.
Maybe in a different way like it is currently handled.
Please understand that this will take a while because we are running this in our spare time.

#### Final words

Thanks for using and contributing to this library.
If there is anything else you would like to tell us, let us know!

**Comment by andygrunwald** [comment]
@Fank Was this closed in favor of #566 ?

(Reopening this until we know why it was closed)

**Comment by Fank** [comment]
> @Fank Was this closed in favor of #566 ?
Yes, no changes will be lost

**Comment by andygrunwald** [comment]
Great, thanks.

**Pull request closed without merging**
