### PR TITLE
Add ISSUE_TEMPLATES to guide users and contributors (for bugs and feature requests)

### PR DESCRIPTION
**Pull request by andygrunwald**
# PR Description

This PR adds two issue-templates and one issue configuration:

* A template for bug reports that ask for details
* A template for feature requests

These templates should help us (maintainers) and users to add all relevant information.
Additionally, it guides users and lets them know what is needed to fulfill such a request.

On top of this, we provide a link to the issue tracker of https://github.com/go-jira/jira
Every now and then, we get issues of the CLI tool go-jira.
(hey @coryb, have a look :) )

The templates are inspired by the Icinga2 project (https://github.com/Icinga/icinga2/tree/master/.github/ISSUE_TEMPLATE). Thanks goes to them!

# Checklist

* [X] Tests added
  * [X] Good Path
  * [x] Error Path
* [x] Commits follow conventions described here:
  * [x] [https://conventionalcommits.org/en/v1.0.0-beta.4/#summary](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [x] [https://chris.beams.io/posts/git-commit/#seven-rules](https://chris.beams.io/posts/git-commit/#seven-rules)
* [X] Commits are squashed such that
  * [X] There is 1 commit per isolated change
* [X] I've not made extraneous commits/changes that are unrelated to my change.

Notes:
* Tests not needed

### CODE REVIEW

**Comment by andygrunwald** [comment]
@ghostsquad If you have a look at this (and +1), I need to adjust the commit message to follow the guidelines. That is what I missed here. I would do it, once this is getting squashed during merge.

**Comment by andygrunwald** [comment]
How do I do it without doing a push force?
Can't we do squash and merge into one? This would change the commit message.

**Comment by ghostsquad** [comment]
@andygrunwald do you know how to interactive rebase? You can squash/edit your commits that way too.

**Comment by ghostsquad** [comment]
@andygrunwald force pushing to a non-trunk branch is A-OK.

**Comment by andygrunwald** [comment]
@ghostsquad I did a push force.
Let me know if you think it should be chore or a different category.

**Pull request merged**
