### PR TITLE
fix(product): Make product naming consistent, rename JIRA to Jira

### PR DESCRIPTION
**Pull request by andygrunwald**
# Description

Atlassian names the product "Jira".
In this library, the product name is used different (JIRA) and
inconsistent (sometimes JIRA, sometimes Jira).

closes issue #284

# Checklist

* [X] Unit or Integration tests added
  * [X] Good Path
  * [X] Error Path
* [X] Commits follow conventions described here:
  * [X] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [X] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [X] Commits are squashed such that
  * [X] There is 1 commit per isolated change
* [X] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Comment by suhaibmujahid** [comment]
I hope you do not merge this PR before reviewing #276 since it will cause conflicts.

**Comment by andygrunwald** [comment]
Thanks for the hint, @suhaibmujahid

**Comment by ghostsquad** [comment]
Happy to approve once conflicts are resolved, and this is rebased.

**Comment by andygrunwald** [comment]
@ghostsquad Here we go :)

**Pull request merged**
