### PR TITLE
feat(auth): Bearer Auth Support (oauth 2.0)

### PR DESCRIPTION
**Pull request by Chhekur**
# Description

Please describe _what does this Pull Request fix or add?_.

Information that is useful here:
* **The What**: Adding support for Bearer based auth method
* **The Why**: Now user can authenticate the client with Bearer token too
* **Type of change**: New Feature
* **Breaking change**: no
* **Related to an issue**: Not sure
* **Jira Version + Type**: Both

## Example:

Let us know how users can use or test this functionality.

```go
tp := jira.BearerAuthTransport {
  Token: "<Bearer Token>"
}

jiraClient, err := jira.NewClient(tp.Client(), host)

```

# Checklist

* [ ] Unit or Integration tests added
  * [ ] Good Path
  * [ ] Error Path
* [x] Commits follow conventions described here:
  * [ ] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [ ] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [x] Commits are squashed such that
  * [ ] There is 1 commit per isolated change
* [ ] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Comment by Chhekur** [comment]
> Hi @andygrunwald! thanks for your library, it's really useful!
> 
> but we have the issue with Jira Server (DC), we need the bearer token for auth.
> 
> Is there a way to speed this PR? thanks! look forward your decision.

Hey, we started maintaining the fork of this library and we update the library very frequently.
so if you still looking for this change you can use our fork for the same and request for new features as well if you want.

https://github.com/interviewstreet/go-jira

**Comment by benjivesterby** [comment]
@Chhekur can you please rebase this on current master branch so I can merge this?

**Comment by Chhekur** [comment]
> @Chhekur can you please rebase this on current master branch so I can merge this?

Hey @benjivesterby,
I rebase it with the current master branch.

**Comment by priteau** [comment]
@benjivesterby, I don't think you should have merged this, since it duplicates the `PATAuthTransport` feature already added in https://github.com/andygrunwald/go-jira/pull/422.

**Pull request merged**
