### PR TITLE
Add "environment" on the issue field

### PR DESCRIPTION
**Pull request by nansuri**
# Description

Please describe _what does this Pull Request fix or add?_.

Information that is useful here:

I need this variable in my project to give environment information on the ticket

# Checklist

* [ ] Unit or Integration tests added
  * [ ] Good Path
  * [ ] Error Path
* [ ] Commits follow conventions described here:
  * [ ] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [ ] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [ ] Commits are squashed such that
  * [ ] There is 1 commit per isolated change
* [ ] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Comment by nansuri** [comment]
hi @andygrunwald could you help me to accept this?

**Comment by andygrunwald** [comment]
Hey @nansuri,

can you point us to the documentation that states support for this field?
Thank you!

**Comment by nansuri** [comment]
well i already try this by myself by adding this line to my local go-jira, but there is the doc @andygrunwald https://docs.atlassian.com/software/jira/docs/api/REST/8.6.0/#api/2/issue-createIssue

**Comment by benjivesterby** [comment]
Looks good to me, the omitempty should keep from any issues with jira versions that do not support it.

**Comment by nansuri** [comment]
seems like the unit test has fail? @andygrunwald

**Review by benjivesterby — APPROVED** [review]

**Pull request merged**
