### PR TITLE
 Fix of Project.Roles Unmarshal Bug

### PR DESCRIPTION
**Pull request by Weiss91**
Add test case to check for completeness of roles unmarshal.
There should be 9 roles in the test, because of the mock/project.json. There are 9 roles given.
Should i comment this in the test?

### CODE REVIEW

**Comment by andygrunwald** [comment]
> If we do go ahead with this, I think we'd have to update to v2 since it's a breaking change.

If this leads to a more functional library or removing limitations (like it sounds), I am fine with it.
It just needs to be mentioned in the release notes.

**Comment by Weiss91** [comment]
V2 works for me, can't think of a backwards-compatible way that isn't a terrible hack.

**Comment by andygrunwald** [comment]
@rbriski I would go ahead with this breaking change. Maybe release a new major version here. This can be combined with #181  for example.

One important thing is a migration guide, where we document what are the breaking changes from version to version and how to migrate. The symfony project is quite good at it. See https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md

**Comment by ghostsquad** [comment]
Project roles are arbitrary, right?
https://confluence.atlassian.com/adminjiracloud/managing-project-roles-776636382.html

Which means, there might not be a "Developer" role in some/most organizations. In fact, I'd guess that this is dead code, as it doesn't actually reflect (or possible to reflect) what roles are actually set up. I'm also ok with merging this breaking change (prior to V2). if these assumptions make sense.

**Comment by ghostsquad** [comment]
Fixes #174

**Comment by Weiss91** [comment]
hey, 
what's the state of this issue? 
Will it be merged before v2? 
If not, what's the planned date for v2?

**Pull request merged**
