### PR TITLE
Finding users by email, username or name

### PR DESCRIPTION
**Pull request by manute**
Hi ,

I'm using this lib and it's very nice. I was trying to find a user by email and I realized that it hasn't got the method for it. So I have created this PR to find users by email, username or name.

It retrieves a list of users and it is based on this https://docs.atlassian.com/jira/REST/cloud/#api/2/user-findUsers

### CODE REVIEW

**Comment by rbriski** [comment]
Not necessarily a review of the code, but if you use the `NewJiraError` function on the returned error like the link below, you'll get more actionable error messages:

https://github.com/andygrunwald/go-jira/blob/master/issue.go#L517

**Comment by manute** [comment]
I have followed the same workflow is used in all the user's methods , so I think that change would be in other PR(for changing all possible methods). 
Otherwise I will mix here methods with that response and other without that response. 
What do you think?

**Comment by rbriski** [comment]
Mmm, good point.  I must have missed the user method return JSON.  I thought I caught them all.  Sounds fine to me although it's obviously up to @andygrunwald

**Comment by rbriski** [comment]
LGTM

**Comment by andygrunwald** [comment]
Thanks @manute for the PR and thanks @rbriski for the review.
In https://github.com/andygrunwald/go-jira/commit/5ac13b726c0a3510c801227997a781cb8f8e3eac i applied the `NewJiraError` function

**Pull request merged**
