### PR TITLE
Fixed bool type for release version

### PR DESCRIPTION
**Pull request by madest92**
Information that is useful here:
* **The What**: Changed bool type to bool pointer
* **The Why**: If you set the fields Archived or Released are `false`, then the fields will not be updated
* **Type of change**: Bugfix
* **Breaking change**: Yes

### CODE REVIEW

**Comment by ghostsquad** [comment]
I will approve given the CI checks pass

**Comment by ghostsquad** [comment]
Oh lol, just the greeting. Nvm

**Review by ghostsquad — APPROVED** [review]

**Comment by ghostsquad** [comment]
I'll give some other maintainers a chance to review before merging.

To the next maintainer: feel free to merge if you also approve.

**Review by benjivesterby — APPROVED** [review]
Looks good to me

**Pull request merged**
