### PR TITLE
GH-400, GH-401 Upgrading JWT Library to V4

### PR DESCRIPTION
**Pull request by benjivesterby**
# Description

Upgraded JWT library to v4 which now has module support as well as resolves security issues listed in GH-400, and GH-401

### CODE REVIEW

**Comment by benjivesterby** [comment]
@andygrunwald @ghostsquad Looks like this upgrade may break pre-1.16 support. Are we ok with that?

**Comment by andygrunwald** [comment]
Also related:
* https://github.com/andygrunwald/go-jira/pull/382
* https://github.com/andygrunwald/go-jira/issues/343

**Review by andygrunwald — APPROVED** [review]
For me, breaking compatibility before go 1.15 is ok. Mainly because the current supported go versions are 1.15, 1.16, and 1.17.
We should follow the release cycle for the language.

The PR looks good. Thanks for taking care. I will move on and merge it.

About the `request_legacy.go` and `request_context.go`, we should think about dropping it at some point.

**Comment by sitikanthasezzle** [comment]
can anybody update new tags or release version to v1.15.0

**Comment by sitikanthasezzle** [comment]
@benjivesterby @andygrunwald

**Pull request merged**
