### PR TITLE
Wrap http.Response in Response struct

### LINKED ISSUE #17: There is no support for pages in responses
go-github wraps http.Response with it's own struct, https://github.com/google/go-github/blob/master/github/github.go#L247 , which has paging-related attributes.

Pagination in JIRA API is described here: https://developer.atlassian.com/confdev/confluence-server-rest-api/pagination-in-the-rest-api

### PR DESCRIPTION
**Pull request by nebril**
The Response struct has StartAt, MaxResults and Total fields, which are
returned from JIRA API in issue search responses. They are now
accessible in Response object.

fixes #17

### CODE REVIEW

**Comment by nebril** [comment]
I forgot about expanding search method to have parameters defining paging. Will add in next commit.

**Comment by andygrunwald** [comment]
Thank you @nebril for this contribution.
I will try to have a look at the weekend in detail. Will this work for you? :)

**Comment by nebril** [comment]
@andygrunwald sure thing, I am using my fork for now, no hurry ;).

**Comment by andygrunwald** [comment]
This is a nice one!
Thank you @nebril!

**Pull request merged**
