### PR TITLE
add issue field 'Affects Version/s'

### PR DESCRIPTION
**Pull request by Tom-Xie**
I found that `IssueFields` struct has a missing field, which is  `Affects Version/s`

`Affects Version/s` has same struct as `Fix Version/s`, however, with different meaning and JSON key as `versions`

### CODE REVIEW

**Comment by andygrunwald** [comment]
Thanks @Tom-Xie.
Can you also extend the unit tests?

**Comment by Tom-Xie** [comment]
Done. 

During the implementation of test, I found both `Affects Version/s` and `Fix Version/s` structs are unnecessary, using `Version` in `version.go` instead.

**Comment by andygrunwald** [comment]
Thank you @Tom-Xie.
For me, this looks good. Also, the change with the `Version` and  `FixVersion` is the better way.

@rbriski How is your opinion here?
Afaik this would be a breaking change because we change types here. I think it is a breaking change in the right direction to avoid duplicate code.

**Comment by rbriski** [comment]
Would this actually break anything?  You should be able to add a struct field but not fill it in, right?

**Comment by Tom-Xie** [comment]
Yes, I think the change is backward compatible, as the extra field could be omitted. @rbriski @andygrunwald

**Comment by ghostsquad** [comment]
Actually, my suggestion doesn't actually make this backward compatible from a client creating a version object to be set in Jira perspective. The only way to do this is to have 2 structs, Version & FixVersion - and accept the unfortunate reality that they have the same fields.

**Comment by ghostsquad** [comment]
Fixed in #209 

@Tom-Xie Thank you for the work you put into this PR! I apologize that I have to close this without merging, I'm trying to ensure that anyone who submits a PR, given it's small enough and meets quality standards can get a merge. But I also want to keep things moving forward, as such, issues/PRs that go stale without response may end up being closed without being merged/addressed.

If you have any additional changes, I'll be attentively watching this repo, and happy to get them merged in!

**Pull request closed without merging**
