### PR TITLE
feat: AddGetBoardConfiguration

### PR DESCRIPTION
**Pull request by 3mard**

### CODE REVIEW

**Comment by andygrunwald** [comment]
Thank you @3mard 
Would you mind to add a unit test also?

**Comment by 3mard** [comment]
Done, thanks.

**Comment by ghostsquad** [comment]
@3mard please rebase and squash those commits, and I think this will be ready for merging then. Thank you for formatting your commit message! :)

**Comment by 3mard** [comment]
🚀

**Pull request merged**
