### PR TITLE
Bugfix/260

### PR DESCRIPTION
**Pull request by evilnerd**
# PR Description
 
This pull request fixes the issue added by me (#260) with 4 commits: 
- 2 commits to fix the issues mentioned (url pre-escaping and endless loop)
- 2 commits to fix and add tests 

# Checklist

* [x] Tests added
  * [x] Good Path
  * [x] Error Path
* [ ] Commits follow conventions described here:
	https://conventionalcommits.org/en/v1.0.0-beta.4/#summary
    https://chris.beams.io/posts/git-commit/#seven-rules
* [x] Commits are squashed such that
  * [x] There is 1 commit per isolated change
* [x] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Comment by evilnerd** [comment]
Please hold, I'm testing this further and running into pagination issues.

**Comment by ghostsquad** [comment]
@evilnerd when you are ready for review, please ensure you've rebased and your commits follow these rules:

  https://conventionalcommits.org/en/v1.0.0-beta.4/#summary
  https://chris.beams.io/posts/git-commit/#seven-rules

**Comment by evilnerd** [comment]
> @evilnerd when you are ready for review, please ensure you've rebased and your commits follow these rules:
> 
> https://conventionalcommits.org/en/v1.0.0-beta.4/#summary
> https://chris.beams.io/posts/git-commit/#seven-rules

Hi, I've rebased (and it said I was up to date) but I'm not quite sure how to change the old commit messages. Should I?

**Comment by ghostsquad** [comment]
@evilnerd sorry, I apologize for the lack of clarity, I mean perform a rebase and "fixup" your commits so that at the _end_ of the rebase, you have 1 commit.

https://git-scm.com/docs/git-rebase

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

prior to rebasing, make sure you've pulled the latest changes in `master` locally.

**Comment by evilnerd** [comment]
Hey Wes,

Thanks for the links. It took me a few attempts but I think I nailed it and
I learned something new in the process (and actually lost 75% of my changes
the first time ;)) -- cool!. I also forwarded the links about commit
messages to my team at work, really good stuff.

Hope the PR is correct now. If not, let me know and I'll try to fix it.

Thanks again!

KR
Dick

Op do 12 mrt. 2020 om 18:47 schreef Wes McNamee <notifications@github.com>:

**Comment by ghostsquad** [comment]
@evilnerd oh no! I'm so sorry you lost some of your work. Changing history can be destructive, so it's definitely not for the faint of heart. I didn't realize you were new to this operation, otherwise I might have suggested to backup the local repo (and thus your commits) prior to rebasing _just in case_.. ;)

I started using a tool to make this easier for me too:

https://github.com/vivaxy/gacp

I highly recommend it. There's still room for improvement of the tool, but it's a great starting point. Also Emoji's are awesome.

**Comment by ghostsquad** [comment]
@evilnerd it looks like you closed this PR was that intentional? Were you going to submit a new PR?

I still see 5 commits in this PR.

If you would like, I can rebase for you, and squash them. I don't want to hang up this PR for too long, as I really appreciate the contributions. I also like linear and succinct Git history. :)

Let me know how I can help.

image

**Comment by evilnerd** [comment]
Hi Wes,

No I removed the branch from github because after rebasing/squashing it
wouldn't push it to the existing branch anymore, and so that closed the PR.
So I created a new PR (#263 -
https://github.com/andygrunwald/go-jira/pull/263)

Sorry for the confusion :)

KR
Dick

Op za 14 mrt. 2020 om 20:03 schreef Wes McNamee <notifications@github.com>:

**Comment by ghostsquad** [comment]
@evilnerd oh I see. Ya, you have to `git push --force` in order to rewrite history of the branch that's in github.

**Pull request closed without merging**
