### PR TITLE
Modified to handle worklog, comment, and updated to be compatible with JIRA's latest version (6.4)

### PR DESCRIPTION
**Pull request by avadhutp**
1. Related issue: #3 
1. I know that for the unit tests, the example JSON from [here](https://docs.atlassian.com/jira/REST/latest/#api/2/issue-getIssue) was used
1. However, this example JSON is either old or has been changed very recently
1. I referred to the sample JSON from [here](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-version-2-tutorial) and this was more reflective of what I saw from my live instance of JIRA 6.4.10

### CODE REVIEW

**Comment by avadhutp** [comment]
FYI, I checked this against JIRA version 6.3, and that works too. For example, see the JSON from https://issues.apache.org/jira/rest/api/2/issue/MESOS-3325

**Comment by andygrunwald** [comment]
Thank you @avadhutp for the PR.
We are running `Atlassian JIRA Project Management Software (v7.1.2#71006-sha1:8e7e309)` (see https://confluence.atlassian.com/jirasoftware/jira-software-release-notes-776821069.html).

I will try to test your changes against this version as well tomorrow or at the weekend.

**Comment by avadhutp** [comment]
@andygrunwald Thanks!

FYI, I checked this branch against [jira.atlassian.com](http://jira.atlassian.com) which runs `v7.1.2#71006-sha1:8e7e309` and it works there too. Here's some example [JSON](https://jira.atlassian.com/rest/api/2/issue/USER-4) from a ticket there.

**Comment by andygrunwald** [comment]
Thank you @avadhutp!

**Pull request merged**
