### PR TITLE
Fix fixversion description field

### PR DESCRIPTION
**Pull request by biohedge**
There's an error: description filed has structs:name, instead of structs:description

### CODE REVIEW

**Comment by ghostsquad** [comment]
@biohedge please amend this commit to follow the standards below:

https://conventionalcommits.org/en/v1.0.0-beta.4/#summary
https://chris.beams.io/posts/git-commit/#seven-rules

an important one often missed is:
https://chris.beams.io/posts/git-commit/#imperative

**Comment by biohedge** [comment]
@ghostsquad Thanks, I've changed the message

**Comment by ghostsquad** [comment]
@biohedge It might seem redundant, but `fix: ` like as it says in conventional commit is also needed here.

`fix: Fix fixversion description tag` is the ideal commit header.

**Comment by biohedge** [comment]
@ghostsquad done

**Pull request merged**
