### PR TITLE
feat: Add ResolutionService to retrieve resolutions

### PR DESCRIPTION
**Pull request by Thiht**
- Add resolution service with GetList
- Add status category related constants (see: https://docs.atlassian.com/DAC/javadoc/jira/reference/com/atlassian/jira/issue/status/category/StatusCategory.html#COMPLETE)
- Add status category service with GetList

### CODE REVIEW

**Comment by Thiht** [comment]
Maybe it's worth adding a GetList function in statuscategory instead? I'll probably need it anyway so I'll try to add it tomorrow :)

**Comment by rbriski** [comment]
OK, so status category includes functions?  From the PR it just looked like you were adding some constants and a struct.  I didn't release there was also an endpoint associated with it.  If there's an endpoint, just keep it in the separate file.

**Comment by Thiht** [comment]
I didn't push the change yet, the StatusCategoryService is in the last commit: 049a756

**Comment by Thiht** [comment]
Would you mind tagging a new release (1.4.0 I guess?) after merging these changes?

**Comment by rbriski** [comment]
Merged and tagged at v1.4

**Comment by Thiht** [comment]
Thanks!

**Pull request merged**
