### PR TITLE
Add ComponentService.Get methods

### PR DESCRIPTION
**Pull request by krrishd**
# Description

Hi!

**What**: Added a `Get` and `GetWithContext` method for `ComponentService`
**Why**: to be able to use `go-jira` to get Project Components (functionality that currently exists in the REST API but not in the library)
**Type of change**: New feature + tests
Also added tests/mock data that effectively mirrors the way we've tested `Get`/`GetWithContext` in `ProjectService`.
**Issue**: This might relate to #361 
**JIRA version + type**: Should work with all JIRA REST API v2, I specifically confirmed with on-prem + 8.17.1 (though I think this feature has been available for much longer)

## Example:

Let us know how users can use or test this functionality.

```go
component, res, err := jiraClient.Component.Get("12345") // 12345 being a component ID, which you can find by going to a list of components, inspecting element, and looking for a data-component-id

```

# Checklist

* [x] Unit or Integration tests added
  * [x] Good Path
  * [x] Error Path
* [x] Commits follow conventions described here:
  * [x] [Conventional Commits 1.0.0](https://conventionalcommits.org/en/v1.0.0-beta.4/#summary)
  * [x] [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/#seven-rules)
* [x] Commits are squashed such that
  * [x] There is 1 commit per isolated change
* [x] I've not made extraneous commits/changes that are unrelated to my change.

### CODE REVIEW

**Review by faizhasim — APPROVED** [review]

**Comment by benjivesterby** [comment]
@andygrunwald any idea why the actions are not available for this PR?

**Comment by andygrunwald** [comment]
@benjivesterby No idea, sorry. never saw it like this.

What do you think about:
1. Applying this change in a local setup
2. Recreating a new branch
3. Pushing it as a new PR

This should trigger the actions.

**Comment by andygrunwald** [comment]
Hey,

I am very sorry that this pull request has been open for a long time with no final feedback or merge/decline. We work on this project in our spare time, and sometimes, other priorities take over. This is the typical open source dilemma.

#### However, there is news: **We are kicking off v2 of this library 🚀** 

To provide visibility, we created the [Road to v2](https://github.com/andygrunwald/go-jira/milestone/1) Milestone and calling for your feedback in https://github.com/andygrunwald/go-jira/issues/489

The development will take some time; however, I hope you can benefit from the changes.
If you seek priority development for your pull request + you like to sponsor it, please contact me.

#### What does this mean for my pull request?

We will work on this pull request indirectly.
We might merge it during the development or pull parts of it into the new version.
This means that during the development phase, we aim to tackle it.
Maybe in a different way like it is currently handled.
Please understand that this will take a while because we are running this in our spare time.

#### Final words

Thanks for using and contributing to this library.
If there is anything else you would like to tell us, let us know!

**Comment by andygrunwald** [comment]
Hey @krrishd,

Thanks again for this pull request. In the recent time, I made various changes to this library (mainly to prep for v2). Hence, your code was not 100% reusable anymore.
I used it as the foundation and made it work in https://github.com/andygrunwald/go-jira/pull/583 again.

Thanks again! Components.Get is now part of the cloud package.

**Pull request closed without merging**
