### PR TITLE
Add filter support for Jira issues

### PR DESCRIPTION
**Pull request by solcates**
Adds #122 

This PR adds support for looking up Issues associated with a FilterID.

The FilterService has 2 methods that i added in the PR.  Get() and GetList() 

While the Jira API v2 says it does support a GetFilters API, i was unable to make a successful API call against a few JIra instances. so Filter.GetList() may or may not work for your environment.

### CODE REVIEW

**Comment by andygrunwald** [comment]
Hey @solcates, just to let you know, I am quite short on time at the moment. This is the reason why a review from my side can take a while. Maybe someone from the community (or @rbriski) can have a more detailed look.
Thanks for understanding and thanks for your contribution!

**Comment by solcates** [comment]
no worries, no rush, we are using our fork for the time being, and i'm sure we'll add a few more features a we start to explore other use cases.

**Comment by rbriski** [comment]
:+1:

**Comment by rbriski** [comment]
This is perfect.  I had started a PR a while ago and just never finished.  This has been merged and a new release has been cut (v1.6.0).  Now all `gopkg.in` links will include this code.

**Pull request merged**
